# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: TestParameter
  displayName: 테스트 파라미터
  type: string
  default: hello world!

trigger:
- none



pool:
  name: Default



steps:
- checkout: none
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo building $(Build.BuildNumber) with ${{ parameters.TestParameter }}
  displayName: 'Run a multi-line script'
